/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.akarsh.spring.rabbitmq;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class AppTest {
    @Test
    public void contextLoads() {}
}
